apiVersion: v1
kind: Service
metadata:
  name: blockchain-svc
  labels:
    app: blockchain
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: 30001
    protocol: TCP
  selector:
    app: blockchain